### ISSUE TITLE
Make some items Ground Storable

### ISSUE THREAD

**Issue by Craluminum2413** [TaskaRaine/Ancient-Tools#14]
Add this behavior to each item in your mod (you can also add it for blocks):
```json
{ "name": "GroundStorable", "properties": { "layout": "Quadrants" } }
```
Including:
``` 
bark.json (add to each behaviorsByType)
saltedmeat.json
salveportion.json
```
Along with that add next changes:

`adzehead.json`:
```json
"attributes": {
  "groundStorageTransform": {
    "translation": { "z": 0.15 }
  }
}
```

`curinghook.json`:
```json
"attributes": {
  "groundStorageTransform": {
        "translation": {
          "y": -0.35
        },
        "scale": 0.95
    }
}
```
`pestle.json`:
```json
"attributes": {
  "groundStorageTransform": {
        "translation": {
          "y": -0.05
        },
        "scale": 0.95
    }
}
```

Please note, that groundStorageTransform can be also edited through command `.tfedit`

**Comment by TaskaRaine** [comment]
Oh wow, thank you for going into so much detail. Leveraging the ground storage system is something I hadn't even considered. There are a bunch of items that really would benefit from using it, especially things like the completed salve components. 

I'll look to getting things working with that system for the next update likely. Thanks!

**Comment by Craluminum2413** [comment]
Note that some items can be placed in Ground Storage only when another item is placed

**Comment by TaskaRaine** [comment]
I've made pestles, curing hooks, bark and adze heads all ground storable. I opted to leave out the salve portion and foods since things like that likely shouldn't be stored on the floor IRL
