### ISSUE TITLE
Bad brainium...

### ISSUE THREAD

**Issue by Nashtyfos** [TaskaRaine/Ancient-Tools#21]
Not sure how to reproduce, but lets have a stab at it...

Made 2 50l barrels with 5 brains each.
Put 8 large and 12 medium hides on the floor holding water.
Maybe logged out and back in...
Waited till they turned.
Used the stretching rack and a tin bronze knife to scrape them.
Tried to put the scraped hides in the brain solution, but they would not seal.
Decided to put them in weak tannin.  :(

I will check back daily to see if you have questions.
Thanks.

**Comment by Nashtyfos** [comment]
Ok...my expectation was I put in 50l of braining solution and the scraped hides would use up as much liquid as they needed, just like putting 12 medium scraped hides in weak tannin...they process, but leave a bit of weak tannin left over.
I tried 40l of braining solution and 10 scraped hides and it would seal.

**Comment by TaskaRaine** [comment]
Oh yea, it needs to be very specific. Which.... I thought the vanilla game also did, but it doesn't! I've got a fix implemented already and will be in the next release ^.^

Thanks for the report!

**Comment by Nashtyfos** [comment]
Cool, so I am not insane!  Dang it!
