### ISSUE TITLE
Make mortar, curing rack and stretching frame carryable with Carry Capacity

### ISSUE THREAD

**Issue by Craluminum2413** [TaskaRaine/Ancient-Tools#24]

**Comment by TaskaRaine** [comment]
The curing rack and stretching frame will both be carryable in the next release. Unfortunately, the mortar can't be carryable as it requires the sneak interact with an empty hand to perform its grinding functions.

**Comment by Craluminum2413** [comment]
You could change interacting to Ctrl + Right-click

**Comment by TaskaRaine** [comment]
Perhaps at a later time. Every held interaction in the mod uses sneak right click interaction, so I'd need to change every held interaction over to keep things consistent.

**Comment by Craluminum2413** [comment]
Or you can add second collision box as grind stone in Necessaries does
