### ISSUE TITLE
Add compatibility with Immersive Crafting

### ISSUE THREAD

**Issue by Craluminum2413** [TaskaRaine/Ancient-Tools#35]
Note that it currently supports only one `liquidStack` per item.
[Example](https://github.com/Craluminum-Mods/ImmersiveCrafting/blob/main/README.md):
```json
{
      "name": "IC_UseOnLiquidContainer",
      "properties": {
        "outputStack": { "type": "item", "code": "dough-{type}", "quantity": 1 },
        "liquidStack": { "type": "item", "code": "waterportion" },
        "actionLangCode": "immersivecrafting:heldhelp-makedough",
        "sound": "sounds/effect/water-fill",
        "consumeLiters": 1,
        "ingredientQuantity": 1,
        "spawnParticles": true
      }
}
```

**Comment by TaskaRaine** [comment]
Note for self:  Add the compatibility for filling up hide water sacks

**Comment by Craluminum2413** [comment]
I update my note too: You can add as many recipes as you want just by adding the same behaviors multiple times
https://github.com/Craluminum-Mods/ImmersiveCrafting/blob/main/README.md
