### ISSUE TITLE
Incompatibility with xrowboat

### ISSUE THREAD

**Issue by WickedSchnitzel** [TaskaRaine/Ancient-Tools#37]
For some reason, if you have both "ancient tools" and "xrowboat" installed, it becomes possible to grind metal tools like axes, cleavers and other items. It may be a problem with xrowboat, but it seems like the author is not active.

**Comment by TaskaRaine** [comment]
Were these the only two mods active? I've given both a test together and can't reproduce it. Ancient Tools uses grindingProps to determine what can be ground down and what can't, just like the vanilla quern does...maybe there's another mod patching that property onto tools? 

The only patches performed by xrowboat seem to be to the player character for animations

**Comment by WickedSchnitzel** [comment]
Yesterday it seemed like it, but today it seems to be "Useful Stuff". Maybe check this one.
https://mods.vintagestory.at/show/mod/25

**Comment by TaskaRaine** [comment]
Ah yea, it is Useful Stuff. Quoted from the mod description: 'Toolheads and tools can be grinded into metal bits in the quern. Metal tools will drop metal bits when they break'

It's an intended feature of the Useful Stuff mod. Ancient Tools mortar is able to grind them down too, just without a dedicated shape to represent the grindable object.

**Comment by WickedSchnitzel** [comment]
Ok, so you want to keep it like that? Because it seems a bit unrealistic.

**Comment by TaskaRaine** [comment]
Yea, I'll keep it as it is.

Sure... it does seem unrealistic. But, I'd rather not sacrifice automatic compatibility with all modded grindables by reinventing the wheel. Besides, it's unlikely that metal tools and metal tool heads could realistically be ground down in a stone quern as is intended by Useful Stuff anyway. 

Still, thanks for bringing this to my attention. I wasn't aware that Useful Stuff allowed tools to be ground down, so it's good knowledge to have
