### ISSUE TITLE
Curing Rack - Description

### ISSUE THREAD

**Issue by Craluminum2413** [TaskaRaine/Ancient-Tools#4]
![image](https://user-images.githubusercontent.com/69315569/128644577-9fe85f00-c5cc-4b8c-be73-b8e678b43cf6.png)
You can fix that by renaming `"item-curinghook-bone": "Bone Curing Hook"` to `"item-curinghook-bone": "\nBone Curing Hook"`,

**Comment by TaskaRaine** [comment]
Huh, I never had that happen. I assumed base.GetPlacedBlockInfo() was putting in a linebreak since it looked right. Guess not, maybe it's just a matter of it being fine on my resolution and not others.

Should be fixed in the next update, thanks for mentioning!

**Comment by Craluminum2413** [comment]
My resolution is 1920x1080

**Comment by Craluminum2413** [comment]
Also they breaking with stone sound

**Comment by TaskaRaine** [comment]
This issue will hopefully be fixed now, and hopefully new blocks don't have the same issues. Please do let me know if things are good on your end if you end up checking it out ^.^

**Comment by Craluminum2413** [comment]
It's okay now.
I found another issue:
![2021-08-30_12-44](https://user-images.githubusercontent.com/69315569/131321413-8ccc4114-fd0b-4870-8ec6-611bdb2d7138.png)

#### Can you also change tooltips to make them more clear? For example:
- "xxxx: Add meat" - **show this tooltip** only when there are 0-3 of meat on the hook, **hide this tooltip** when hook is missing or there are 4 meat on the hook
- "xxx: Add hook" - **show this tooltip** only when hook amount are less then 4 or when hook is missing

#### Also add these tooltips:
- "xxxx: Remove meat" - **show this tooltip** only when there is at least 1 meat on hook, **hide this tooltip** when meat is missing
- "xxxx: Remove hook" - **hide this tooltip** when there is at least 1 meat or hook is missing

**Comment by TaskaRaine** [comment]
Both of those issues are now fixed and will be in the next release ^.^

If you want to solve the obstructed number with the hooks immediately, all you'll need to do is navigate through the Ancient Tools asset folder as follows...

assets/ancienttools/itemtypes/curinghook.json

...and change the guiTransform object to this:
guiTransform: {
		translation: { x: 3, y: 0, z: -40 },
		rotation: { x: 0, y: 45, z: 180 },
		origin: { x: 0, y: 0.5, z: 0 },
		scale: 4.5
	},

**Comment by TaskaRaine** [comment]
Update's out, both fixes should be official now ^.^. Thank you!
