### ISSUE TITLE
Curing meat not working

### ISSUE THREAD

**Issue by Stin045** [TaskaRaine/Ancient-Tools#40]
I know to place rack , place hooks, put meat and wait but it turned into -6 days to cure and meat was still raw

**Comment by TaskaRaine** [comment]
I imagine you were away from the area for an extended period of time, with the chunk unloaded, and returned to see this? If not, please let me know some more details.

Seems there was some strangeness in one of the logic checks that caused this. It should be fixed for the next release, just got to test it a little more. Thanks for the report!

If you see this again, just wait an in-game hour. When the curing rack does another tick it should cure the things.

**Comment by TaskaRaine** [comment]
This should now be fixed in Ancient Tools V1.4.4. If you have the chance to confirm, please do let me know what you find ^.^
