### ISSUE TITLE
1.18.5 Endless error spam, causes server to basically lock up

### ISSUE THREAD

**Issue by RogueRaiden** [TaskaRaine/Ancient-Tools#64]
unsure of the cause, spams this error until i force closed the server.

[https://pastebin.com/itywweMp](https://pastebin.com/itywweMp)

**Comment by TaskaRaine** [comment]
Seems I missed a null check in the cart repair code, yep. This error is thrown when the mouse drifts off of the cart hitbox during repairs. This will be fixed in the next release. 

Thanks for the report!

**Comment by TaskaRaine** [comment]
Should be all fixed up in the latest release, Ancient Tools 1.5.5 ^_^
