### ISSUE TITLE
Curing Meat in Barrels no longer works - recipe is disabled

### ISSUE THREAD

**Issue by drenidor** [TaskaRaine/Ancient-Tools#65]
Tried both meat types with double the amount salt (64:32) in a barrel but you can't seal it anymore. 

Recipe on how to mix in a barrel with the correct ration is no longer visible in the handbook:
![image](https://github.com/TaskaRaine/Ancient-Tools/assets/5357826/7d482a4c-8233-4305-a64a-ce4dbe2f1695)

**Comment by TaskaRaine** [comment]
Uuuh, there must be some other mod causing this to happen. With only Ancient Tools and Meteoric Expansion running the recipe appears in the handbook as normal. This is using Ancient Tools 1.5.4 on Vintage Story 1.18.5

Feel free to post your mod list and I'll try and help figure out which mod it may be. I'd like to know, too, for curiosity's sake xD

![CuredRedmeatRecipe](https://github.com/TaskaRaine/Ancient-Tools/assets/53409481/61d48300-bef1-48f7-adaf-e4537c42ddea)

**Comment by drenidor** [comment]
Indeed, sorry for bothering! The mod which caused the recipe to disappear was 'Fauna of the Stone Age: Capreolinae' - thanks for the offered help!

**Comment by TaskaRaine** [comment]
Wonderful! Glad you found the cause of the issue. From what I'm reading, they've already fixed the problem with their 1.0.1 mod release ^.^
