### ISSUE TITLE
Can drop carts in claimed areas and then be locked out of getting the cart back lol

### ISSUE THREAD

**Issue by RogueRaiden** [TaskaRaine/Ancient-Tools#70]
the title.

have had a few players now drop carts in claims or in our server marketplace and are unable to get them back cause of the claim protection

**Comment by TaskaRaine** [comment]
Oh jeeze lol, didn't think of that possibility. I'll try to think of some solution. Maybe the creator could always have permission to pick up the cart

**Comment by RogueRaiden** [comment]
Maybe If the cart would remember who dropped it and only allow that person to pick back up for a time

**Comment by RogueRaiden** [comment]
Maybe If the cart would remember who dropped it and only allow that person to pick back up for a time

**Comment by TaskaRaine** [comment]
Maybe even both could work ^_^

**Comment by TaskaRaine** [comment]
I've posted an update(1.5.6) to the mod on the Vintage Story ModDB that should address this. Cart owners now always have access to their carts regardless of the claim it is in. Also, they remember their previous hauler and, when in other player claims, the hauler can still pick up the cart and access its inventory.

Thanks for the report! If there are any further issues please do let me know by reopening this, or other, issues. It's hard for me to discover server-related issues like these
