### ISSUE TITLE
Support beams placed on chiseled blocks can't be broken

### ISSUE THREAD

**Issue by conninator2000** [TaskaRaine/Ancient-Tools#72]
A support beam attached to a chiseled block will attach itself to that entity. When that block is picked up or moved the support beam will come with it (and can't be broken)

Creating a support beam from a chiseled block (the support starts not connected to the block)
![image](https://github.com/TaskaRaine/Ancient-Tools/assets/68338085/b8e31778-88a5-41e3-8be8-7a4701105824)

The beam attaches to a building
![image](https://github.com/TaskaRaine/Ancient-Tools/assets/68338085/87dcd019-3224-48bb-a82d-19769504c0a7)

If the chisel block is removed, the support beam comes with it
![image](https://github.com/TaskaRaine/Ancient-Tools/assets/68338085/b88f775d-b826-4899-bc8e-2f8a1ad83c22)

If it is placed again, the beam comes with it at the same length/angle it had prior
![image](https://github.com/TaskaRaine/Ancient-Tools/assets/68338085/640cddb1-abf0-44be-a8d8-694736749e12)

And it has no connection to break to remove the beam
![image](https://github.com/TaskaRaine/Ancient-Tools/assets/68338085/c6d4174a-91cb-4165-9246-6784f68f4b23)

**Comment by Craluminum2413** [comment]
@conninator2000 support beams are vanilla, it is purely vanilla bug

**Comment by TaskaRaine** [comment]
Yup, as Craluminum said, these beams are actually a vanilla feature. Ancient Tools just has an alternative, immersive means of creating them. I had created a simpler form of beams in Ancient Tools for VS 1.17, before they were introduced to VS 1.18. They still exist in game but do nothing more than stack in a pile in-world

**Comment by conninator2000** [comment]
Update: I just realized that place-able support beams is a vanilla bug and has already been reported... oops!
