### ISSUE TITLE
Client crash on rendering a cart

### ISSUE THREAD

**Issue by RogueRaiden** [TaskaRaine/Ancient-Tools#74]
[https://pastebin.com/NMA5dqhN](https://pastebin.com/NMA5dqhN)

so a player says they were in the cart inventory and pressed a "sort" button and now any client who loads the cart crashes out of the server.

**Comment by RogueRaiden** [comment]
sort button is from [Xandus Inventory Tweaks](https://mods.vintagestory.at/show/mod/367)

**Comment by RogueRaiden** [comment]
was able to get around it by disabling the cart entity and loading the world, causing it to not exist

**Comment by TaskaRaine** [comment]
Oh dear, that mod gets applied to carts? :V 

They were not designed with sort-ability in mind. The inventory object(the chest) on the cart always needs to be the very first object in the inventory, that way I can access specific attributes that tell the cart all sorts of information about the inventory object. Whatever object is taking that space, if any, doesn't have those same attributes that it's expecting and causing issues. Even if it didn't crash... there's no way for the client to know how many slots are in that inventory anymore so none of the items would even be accessible without breaking the cart itself. 

I don't know if there's a quick way of solving this problem. I could separate it into two independent inventories... that should solve the problem in this specific case. But as soon as I try to extend to support multiple inventory blocks... there's still going to be wonkiness if those blocks themselves get sorted. Either way, things would need to be refactored, unfortunately

**Comment by TaskaRaine** [comment]
It looks like Xandu released an update to Xandus Inventory Tweaks which adds a blacklist for the sorting feature. Ancient Tools carts are on the blacklist by default ^_^
