### ISSUE TITLE
Don't work on 1.19 pre-7/8/9

### ISSUE THREAD

**Issue by WH3Re9Tr03** [TaskaRaine/Ancient-Tools#79]
![image](https://github.com/TaskaRaine/Ancient-Tools/assets/126208266/38d64c0c-83ae-4600-9862-ff4247ee311e)
Just this in logs

**Comment by TaskaRaine** [comment]
Ancient Tools has not yet been updated to be compatible with Vintage Story 1.19. I typically wait until release candidate versions of a major release to avoid pre-release API changes

**Comment by TaskaRaine** [comment]
Ancient Tools 1.5.12 has just been released and should work with Vintage Story 1.19.0 ^_^
